### ISSUE TITLE
reciebing block is not implemented

### ISSUE THREAD

**Issue by furesoft** [danielgerlag/NBlockchain#14]

**Comment by danielgerlag** [comment]
Could you give some more details?

**Comment by furesoft** [comment]
![image](https://user-images.githubusercontent.com/4117602/56042265-f582ff00-5d3a-11e9-97f4-2e8e24eeaae9.png)

**Comment by danielgerlag** [comment]
What does your IoC container setup look like?

**Comment by furesoft** [comment]
its the sample application using litedb as provider

**Comment by danielgerlag** [comment]
I can't reproduce this issue... could you try re-clone the repo and try again?
