### ISSUE TITLE
Unable to resolve service for type 

### ISSUE THREAD

**Issue by furesoft** [danielgerlag/NBlockchain#16]
Unable to resolve service for type 'System.String' while attempting to activate 'NBlockchain.Services.NatTraversal.UpnpAutodetectPortForwarding'."

when trying to use UseTcpPeerNetwork();

**Comment by danielgerlag** [comment]
What does your IoC container setup look like?

**Comment by furesoft** [comment]
its the sample application using litedb as provider

**Comment by danielgerlag** [comment]
Seems to be an issue with the NatTraversal services... I've updated the sample like this
```
x.UseNoNatTraversal();
```
Which is now working
